[tools]
deno = "2.1.5"
vale = "3.9.3"
jj = "latest"

[tasks.serve]
run = """
    deno run --allow-net=0.0.0.0:8080 \
             --allow-env \
             --allow-sys=cpus \
             --allow-read=./,"$HOME/.cache/deno/node_modules","$HOME/.cache/node_modules","$HOME/node_modules","/home/node_modules","/node_modules" \
             --allow-write=_site/ \
             npm:@11ty/eleventy --serve --port 8080
"""

[tasks.build]
run = """
    deno run --allow-env \
             --allow-sys=cpus \
             --allow-read=./,"$HOME/.cache/deno/node_modules","$HOME/.cache/node_modules","$HOME/node_modules","/home/node_modules","/node_modules" \
             --allow-write=_site/ \
             npm:@11ty/eleventy
"""

[tasks.update-resume]
run = """
    git clone git@github.com:ishehadeh/resume.git
    cd resume
    git checkout {{arg(name="version", default='main')}}
    cp resume.technical.pdf ../www/assets/shehadeh-ian-resume.pdf
    cd ..
    rm -rf resume
"""

[tasks.lint]
run = "vale ./www/"
