name: Deploy to GitHub Pages
#  source: https://www.11ty.dev/docs/deployment/, and https://raw.githubusercontent.com/corbindavenport/corbindavenport.github.io/refs/heads/main/.github/workflows/eleventy_build.yml accessed 1/21/2025
on:
  push:
    branches:
      - master
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Build site
      run: npx @11ty/eleventy

    - name: Update pages artifact
      uses: actions/upload-pages-artifact@v3.0.1
      with:
        path: _site/

  deploy:
    needs: build
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${\{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    steps:
    - name: Deploy to GitHub Pages
      id: deployment
      uses: actions/deploy-pages@v4
