name: Deploy to GitHub Pages
#  source: https://www.11ty.dev/docs/deployment/, accessed 1/21/2025
on:
  push:
    branches:
      - main
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-22.04
    permissions:
      pages: write
      id-token: write
    concurrency:
      group: ${{ github.workflow }}-${{ github.ref }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    steps:
      - uses: actions/deploy-pages@v4
      - run: |
        curl https://mise.run | sh
        echo "$HOME/.local/share/mise/bin" >> $GITHUB_PATH
        echo "$HOME/.local/share/mise/shims" >> $GITHUB_PATH
      - run: mise install
      - run: npm run build

      - name: Deploy artifact
        id: deployment
        uses: actions/deploy-pages@v4
        artifact: _site/